options:
  dcf_path: "@BUS_CONFIG_PATH@"

master:
  node_id: 10
  driver: "ros2_canopen::MasterDriver"
  package: "canopen_master_driver"
  sync_period: 1000  


  
# first_shaft_joint:
#   node_id: 2
#   dcf: "PD4-C6018L4204-E-08.eds"
#   driver: "ros2_canopen::Cia402Driver"
#   package: "canopen_402_driver"
#   polling: true
#   period: 10
#   diagnostics:
#     enable: false
#     period: 1000

#     # Change the scale to correspond to the real hardware : 
#   scale_pos_to_dev : 1.0
#   scale_vel_to_dev : 1.0
#   scale_pos_from_dev : 0.001
#   scale_vel_from_dev : 0.001
  
#   heartbeat_producer: 2000
  
#   sdo: # SDO executed during config
#     - {index: 0x6081, sub_index: 0, value: 500000} # Set velocity 
#     - {index: 0x6083, sub_index: 0, value: 1000000} # Set acceleration
#     - {index: 0x6083, sub_index: 0, value: 1000000} # Set deceleration
#     - {index: 0x6085, sub_index: 0, value: 1000000} # Set quickstop deceleration
#     - {index: 0x6060, sub_index: 0, value: 1} # Set profile position mode
#     - {index: 0x6098, sub_index: 0, value: 35} # Set default homing mode to 35
#     - {index: 0x60C2, sub_index: 1, value: 50} # Set interpolation time for cyclic modes to 50 ms
#     - {index: 0x60C2, sub_index: 2, value: -3} # Set base 10-3s


# second_shaft_joint:
#   node_id: 2
#   dcf: "PD4-C6018L4204-E-08.eds"
#   driver: "ros2_canopen::Cia402Driver"
#   package: "canopen_402_driver"
#   polling: true
#   period: 10
#   diagnostics:
#     enable: false
#     period: 1000

#     # Change the scale to correspond to the real hardware : 
#   scale_pos_to_dev : 1.0
#   scale_vel_to_dev : 1.0
#   scale_pos_from_dev : 0.001
#   scale_vel_from_dev : 0.001
  
#   heartbeat_producer: 2000
  
#   sdo: # SDO executed during config
#     - {index: 0x6081, sub_index: 0, value: 500000} # Set velocity 
#     - {index: 0x6083, sub_index: 0, value: 1000000} # Set acceleration
#     - {index: 0x6083, sub_index: 0, value: 1000000} # Set deceleration
#     - {index: 0x6085, sub_index: 0, value: 1000000} # Set quickstop deceleration
#     - {index: 0x6060, sub_index: 0, value: 1} # Set profile position mode
#     - {index: 0x6098, sub_index: 0, value: 35} # Set default homing mode to 35
#     - {index: 0x60C2, sub_index: 1, value: 50} # Set interpolation time for cyclic modes to 50 ms
#     - {index: 0x60C2, sub_index: 2, value: -3} # Set base 10-3s



third_shaft_joint:
  node_id: 2
  dcf: "PD4-C6018L4204-E-08.eds"
  driver: "ros2_canopen::Cia402Driver"
  package: "canopen_402_driver"
  polling: true
  period: 10
  diagnostics:
    enable: true
    period: 1000

    # Change the scale to correspond to the real hardware : 
  scale_pos_to_dev : 1.0
  scale_vel_to_dev : 1.0
  scale_pos_from_dev : 0.001
  scale_vel_from_dev : 0.001
  
  heartbeat_producer: 2000
  
  sdo: # SDO executed during config
    - {index: 0x6081, sub_index: 0, value: 100} # Set velocity 
    - {index: 0x6083, sub_index: 0, value: 1000} # Set acceleration
    - {index: 0x6083, sub_index: 0, value: 1000} # Set deceleration
    - {index: 0x6085, sub_index: 0, value: 10000} # Set quickstop deceleration
    - {index: 0x6060, sub_index: 0, value: 1} # Set profile position mode
    - {index: 0x6098, sub_index: 0, value: 35} # Set default homing mode to 35
    - {index: 0x60C2, sub_index: 1, value: 50} # Set interpolation time for cyclic modes to 50 ms
    - {index: 0x60C2, sub_index: 2, value: -3} # Set base 10-3s

  

# fourth_shaft_joint:
#   node_id: 1
#   dcf: "PD4-CB59M024035-E-08.eds"
#   driver: "ros2_canopen::Cia402Driver"
#   package: "canopen_402_driver"
#   polling: true
#   period: 10
#   position_mode: 1
#   diagnostics:
#     enable: false
#     period: 1000

#     # Change the scale to correspond to the real hardware : 
#   scale_pos_to_dev : 1.0
#   scale_vel_to_dev : 1.0
#   scale_pos_from_dev : 0.000303951 #3.29
#   scale_vel_from_dev : 0.001
  
#   heartbeat_producer: 2000
  
#   sdo: # SDO executed during config
#     - {index: 0x6081, sub_index: 0, value: 0x000001F4} # Set velocity 
#     - {index: 0x6083, sub_index: 0, value: 300} # Set acceleration
#     - {index: 0x6084, sub_index: 0, value: 300} # Set deceleration
#     - {index: 0x6085, sub_index: 0, value: 1000} # Set quickstop deceleration
#     - {index: 0x6060, sub_index: 0, value: 1} # Set profile position mode
#     - {index: 0x6098, sub_index: 0, value: 35} # Set default homing mode to 35
#     - {index: 0x60C2, sub_index: 1, value: 50} # Set interpolation time for cyclic modes to 50 ms
#     - {index: 0x60C2, sub_index: 2, value: -3} # Set base 10-3s
#     - {index: 0x60A8, sub_index: 0, value: 0x00B40000} # Set position unit to rev
