options:
  dcf_path: "@BUS_CONFIG_PATH@"

master:
  node_id: 10
  driver: "ros2_canopen::MasterDriver"
  package: "canopen_master_driver"
  sync_period: 1000  


  
first_shaft_joint:
  node_id: 1
  dcf: "PD4-C6018L4204-E-08.eds"
  driver: "ros2_canopen::Cia402Driver"
  package: "canopen_402_driver"
  polling: true
  period: 10
  diagnostics:
    enable: true
    period: 1000

    # Change the scale to correspond to the real hardware : 
  scale_pos_to_dev : 1.0
  scale_vel_to_dev : 1.0
  scale_eff_to_dev : 1.0
  scale_pos_from_dev : 1.0
  scale_vel_from_dev : 1.0
  scale_eff_from_dev : 1.0
  
  heartbeat_producer: 2000
  
  sdo: # SDO executed during config
    - {index: 0x3240, sub_index: 2, value: 1} # Function inverted
    - {index: 0x6081, sub_index: 0, value: 50} # Set velocity 
    - {index: 0x6083, sub_index: 0, value: 1000} # Set acceleration
    - {index: 0x6084, sub_index: 0, value: 1000} # Set deceleration
    - {index: 0x6085, sub_index: 0, value: 10000} # Set quickstop deceleration
    - {index: 0x6060, sub_index: 0, value: 1} # Set profile position mode
    - {index: 0x6098, sub_index: 0, value: 17} # Set default homing mode to 35
    - {index: 0x60C2, sub_index: 1, value: 50} # Set interpolation time for cyclic modes to 50 ms
    - {index: 0x60C2, sub_index: 2, value: -3} # Set base 10-3s
    - {index: 0x60C4, sub_index: 6, value: 1} # Interpolated position mode needed param 
    - {index: 0x60C6, sub_index: 0, value: 1000} # Max Acceleration
    - {index: 0x607D, sub_index: 1, value: 0} # Min Position
    - {index: 0x607D, sub_index: 2, value: 257040} # Max Position
    - {index: 0x3240, sub_index: 1, value: 1} # Special function enable
    # 
    # - {index: 0x6098, sub_index: 0, value: 17} # Homing method

  tpdo: 
    1:
        enabled: true
        cob_id: "auto"
        transmission: 0x01
        mapping:
            - {index: 0x6041, sub_index: 0} 
            - {index: 0x6041, sub_index: 0} 
    2:
        enabled: true
        cob_id: "auto"
        transmission: 0x01
        mapping:
            - {index: 0x6061, sub_index: 0} 
            - {index: 0x6041, sub_index: 0} 
    3:
        enabled: true
        cob_id: "auto"
        transmission: 0x01
        mapping:
            - {index: 0x6064, sub_index: 0} 
            - {index: 0x6041, sub_index: 0} 
    4:
        enabled: true
        cob_id: "auto"
        transmission: 0x01
        mapping:
            - {index: 0x606C, sub_index: 0} 
            - {index: 0x6077, sub_index: 0} 
  rpdo: 
    1:
        enabled: true
        cob_id: "auto"
        transmission: 0x01
        mapping:
        - {index: 0x6040, sub_index: 0} 
        - {index: 0x6040, sub_index: 0} 
    2:
        enabled: true
        cob_id: "auto"
        transmission: 0x01
        mapping:
        - {index: 0x6060, sub_index: 0} 
        - {index: 0x6040, sub_index: 0} 
    3:
        enabled: true
        cob_id: "auto"
        transmission: 0x01
        mapping:
        - {index: 0x607A, sub_index: 0} 
        - {index: 0x6040, sub_index: 0}     
    4:
        enabled: true
        cob_id: "auto"
        transmission: 0x01
        mapping:
        - {index: 0x60FF, sub_index: 0}
        - {index: 0x6071, sub_index: 0}  



second_shaft_joint:
  node_id: 2
  dcf: "PD4-C6018L4204-E-08.eds"
  driver: "ros2_canopen::Cia402Driver"
  package: "canopen_402_driver"
  polling: true
  period: 10
  diagnostics:
    enable: true
    period: 1000

    # Change the scale to correspond to the real hardware : 
  scale_pos_to_dev : 1.0
  scale_vel_to_dev : 1.0
  scale_eff_to_dev : 1.0
  scale_pos_from_dev : 1.0
  scale_vel_from_dev : 1.0
  scale_eff_from_dev : 1.0
  
  heartbeat_producer: 2000
  
  sdo: # SDO executed during config
    - {index: 0x3240, sub_index: 2, value: 1} # Function inverted
    - {index: 0x6081, sub_index: 0, value: 50} # Set velocity 
    - {index: 0x6083, sub_index: 0, value: 1000} # Set acceleration
    - {index: 0x6084, sub_index: 0, value: 1000} # Set deceleration
    - {index: 0x6085, sub_index: 0, value: 10000} # Set quickstop deceleration
    - {index: 0x6060, sub_index: 0, value: 1} # Set profile position mode
    - {index: 0x6098, sub_index: 0, value: 17} # Set default homing mode to 35
    - {index: 0x60C2, sub_index: 1, value: 50} # Set interpolation time for cyclic modes to 50 ms
    - {index: 0x60C2, sub_index: 2, value: -3} # Set base 10-3s
    - {index: 0x60C4, sub_index: 6, value: 1} # Interpolated position mode needed param 
    - {index: 0x60C6, sub_index: 0, value: 1000} # Max Acceleration
    - {index: 0x607D, sub_index: 1, value: 0} # Min Position
    - {index: 0x607D, sub_index: 2, value: 257040} # Max Position  408240
    - {index: 0x3240, sub_index: 1, value: 1} # Special function enable
    
    # - {index: 0x6098, sub_index: 0, value: 17} # Homing method


  tpdo: 
    1:
        enabled: true
        cob_id: "auto"
        transmission: 0x01
        mapping:
            - {index: 0x6041, sub_index: 0} 
            - {index: 0x6041, sub_index: 0} 
    2:
        enabled: true
        cob_id: "auto"
        transmission: 0x01
        mapping:
            - {index: 0x6061, sub_index: 0} 
            - {index: 0x6041, sub_index: 0} 
    3:
        enabled: true
        cob_id: "auto"
        transmission: 0x01
        mapping:
            - {index: 0x6064, sub_index: 0} 
            - {index: 0x6041, sub_index: 0} 
    4:
        enabled: true
        cob_id: "auto"
        transmission: 0x01
        mapping:
            - {index: 0x606C, sub_index: 0} 
            - {index: 0x6077, sub_index: 0} 
  rpdo: 
    1:
        enabled: true
        cob_id: "auto"
        transmission: 0x01
        mapping:
        - {index: 0x6040, sub_index: 0} 
        - {index: 0x6040, sub_index: 0} 
    2:
        enabled: true
        cob_id: "auto"
        transmission: 0x01
        mapping:
        - {index: 0x6060, sub_index: 0} 
        - {index: 0x6040, sub_index: 0} 
    3:
        enabled: true
        cob_id: "auto"
        transmission: 0x01
        mapping:
        - {index: 0x607A, sub_index: 0} 
        - {index: 0x6040, sub_index: 0}     
    4:
        enabled: true
        cob_id: "auto"
        transmission: 0x01
        mapping:
        - {index: 0x60FF, sub_index: 0}
        - {index: 0x6071, sub_index: 0}  



third_shaft_joint:
  node_id: 3
  dcf: "PD4-C6018L4204-E-08.eds"
  driver: "ros2_canopen::Cia402Driver"
  package: "canopen_402_driver"
  polling: true
  period: 10
  diagnostics:
    enable: true
    period: 1000

    # Change the scale to correspond to the real hardware : 
  scale_pos_to_dev : 1.0
  scale_vel_to_dev : 1.0
  scale_eff_to_dev : 1.0
  scale_pos_from_dev : 1.0
  scale_vel_from_dev : 1.0
  scale_eff_from_dev : 1.0
  
  heartbeat_producer: 2000
  
  sdo: # SDO executed during config
    - {index: 0x3240, sub_index: 2, value: 1} # Function inverted
    - {index: 0x6081, sub_index: 0, value: 50} # Set velocity 
    - {index: 0x6083, sub_index: 0, value: 1000} # Set acceleration
    - {index: 0x6084, sub_index: 0, value: 1000} # Set deceleration
    - {index: 0x6085, sub_index: 0, value: 10000} # Set quickstop deceleration
    - {index: 0x6060, sub_index: 0, value: 1} # Set profile position mode
    # - {index: 0x6098, sub_index: 0, value: 35} # Set default homing mode to 35
    - {index: 0x60C2, sub_index: 1, value: 50} # Set interpolation time for cyclic modes to 50 ms
    - {index: 0x60C2, sub_index: 2, value: -3} # Set base 10-3s
    - {index: 0x60C4, sub_index: 6, value: 1} # Interpolated position mode needed param 
    - {index: 0x60C6, sub_index: 0, value: 1000} # Max Acceleration
    - {index: 0x607D, sub_index: 1, value: 0} # Min Position
    - {index: 0x607D, sub_index: 2, value: 144000} # Max Position
    - {index: 0x6098, sub_index: 0, value: 17} # Homing method
    - {index: 0x3240, sub_index: 1, value: 1} # Special function enable
    # - {index: 0x3701, sub_index: 0, value: -1} # Limit Switch Error Option Code

  tpdo: 
    1:
        enabled: true
        cob_id: "auto"
        transmission: 0x01
        mapping:
            - {index: 0x6041, sub_index: 0} 
            - {index: 0x6041, sub_index: 0} 
    2:
        enabled: true
        cob_id: "auto"
        transmission: 0x01
        mapping:
            - {index: 0x6061, sub_index: 0} 
            - {index: 0x6041, sub_index: 0} 
    3:
        enabled: true
        cob_id: "auto"
        transmission: 0x01
        mapping:
            - {index: 0x6064, sub_index: 0} 
            - {index: 0x6041, sub_index: 0} 
    4:
        enabled: true
        cob_id: "auto"
        transmission: 0x01
        mapping:
            - {index: 0x606C, sub_index: 0} 
            - {index: 0x6077, sub_index: 0} 
  rpdo: 
    1:
        enabled: true
        cob_id: "auto"
        transmission: 0x01
        mapping:
        - {index: 0x6040, sub_index: 0} 
        - {index: 0x6040, sub_index: 0} 
    2:
        enabled: true
        cob_id: "auto"
        transmission: 0x01
        mapping:
        - {index: 0x6060, sub_index: 0} 
        - {index: 0x6040, sub_index: 0} 
    3:
        enabled: true
        cob_id: "auto"
        transmission: 0x01
        mapping:
        - {index: 0x607A, sub_index: 0} 
        - {index: 0x6040, sub_index: 0}     
    4:
        enabled: true
        cob_id: "auto"
        transmission: 0x01
        mapping:
        - {index: 0x60FF, sub_index: 0}
        - {index: 0x6071, sub_index: 0}  
  


fourth_shaft_joint:
  node_id: 4
  dcf: "PD4-CB59M024035-E-08.eds"
  driver: "ros2_canopen::Cia402Driver"
  package: "canopen_402_driver"
  polling: true
  period: 10
  diagnostics:
    enable: false
    period: 1000

    # Change the scale to correspond to the real hardware : 
  scale_pos_to_dev : 1.0
  scale_vel_to_dev : 1.0
  scale_eff_to_dev : 1.0
  scale_pos_from_dev : 1.0
  scale_vel_from_dev : 1.0
  scale_eff_from_dev : 1.0
  
  heartbeat_producer: 2000
  
  sdo: # SDO executed during config
    - {index: 0x6081, sub_index: 0, value: 200} # Set velocity 
    - {index: 0x6083, sub_index: 0, value: 1000} # Set acceleration
    - {index: 0x6084, sub_index: 0, value: 1000} # Set deceleration
    - {index: 0x6085, sub_index: 0, value: 10000} # Set quickstop deceleration
    - {index: 0x6060, sub_index: 0, value: 6} # Set profile position mode
    - {index: 0x6098, sub_index: 0, value: 35} # Set default homing mode to 35
    - {index: 0x60C2, sub_index: 1, value: 50} # Set interpolation time for cyclic modes to 50 ms
    - {index: 0x60C2, sub_index: 2, value: -3} # Set base 10-3s
    - {index: 0x60C4, sub_index: 6, value: 1} # Interpolated position mode needed param 
    - {index: 0x60C6, sub_index: 0, value: 1000} # Max Acceleration
    - {index: 0x607D, sub_index: 1, value: 0} # Min Position
    - {index: 0x607D, sub_index: 2, value: 551232} # Max Position

  tpdo: 
    1:
        enabled: true
        cob_id: "auto"
        transmission: 0x01
        mapping:
            - {index: 0x6041, sub_index: 0} 
            - {index: 0x6041, sub_index: 0} 
    2:
        enabled: true
        cob_id: "auto"
        transmission: 0x01
        mapping:
            - {index: 0x6061, sub_index: 0} 
            - {index: 0x6041, sub_index: 0} 
    3:
        enabled: true
        cob_id: "auto"
        transmission: 0x01
        mapping:
            - {index: 0x6064, sub_index: 0} 
            - {index: 0x6041, sub_index: 0} 
    4:
        enabled: true
        cob_id: "auto"
        transmission: 0x01
        mapping:
            - {index: 0x606C, sub_index: 0} 
            - {index: 0x6077, sub_index: 0} 
  rpdo: 
    1:
        enabled: true
        cob_id: "auto"
        transmission: 0x01
        mapping:
        - {index: 0x6040, sub_index: 0} 
        - {index: 0x6040, sub_index: 0} 
    2:
        enabled: true
        cob_id: "auto"
        transmission: 0x01
        mapping:
        - {index: 0x6060, sub_index: 0} 
        - {index: 0x6040, sub_index: 0} 
    3:
        enabled: true
        cob_id: "auto"
        transmission: 0x01
        mapping:
        - {index: 0x607A, sub_index: 0} 
        - {index: 0x6040, sub_index: 0}     
    4:
        enabled: true
        cob_id: "auto"
        transmission: 0x01
        mapping:
        - {index: 0x60FF, sub_index: 0}
        - {index: 0x6071, sub_index: 0}  



