controller_manager:
  ros__parameters:
    update_rate: 10  # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # robot_controller_first:
      # type: canopen_ros2_controllers/Cia402DeviceController

    # robot_controller_second:
    #   type: canopen_ros2_controllers/Cia402DeviceController

    robot_controller_third:
      type: canopen_ros2_controllers/Cia402DeviceController

    # joint_trajectory_controller:
    #   type: joint_trajectory_controller/JointTrajectoryController

    # forward_position_controller:
    #   type: forward_command_controller/ForwardCommandController


# robot_controller_first:
#   ros__parameters:
#       joint: first_shaft_joint

# robot_controller_second:
#   ros__parameters:
#       joint: second_shaft_joint

robot_controller_third:
  ros__parameters:
      joint: third_shaft_joint


# forward_position_controller:
#   ros__parameters:
#     joints:
#       - first_shaft_joint
#       - second_shaft_joint
#       - third_shaft_joint
#     interface_name: position

# joint_trajectory_controller:
#   ros__parameters:
#     joints:
#       - first_shaft_joint
#       - second_shaft_joint
#       - third_shaft_joint
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity
#     state_publish_rate: 100.0
#     action_monitor_rate: 20.0
#     allow_partial_joints_goal: false
#     constraints:
#       stopped_velocity_tolerance: 0.2
#       goal_time: 0.0
#       second_shaft_joint: { trajectory: 0.2, goal: 0.1 }
